css/init.css, index.html, js/init.js
Adjusted the position of navbar links, added smooth scroll feature, and removed a bit of irrelevant CSS/JS.
**Video (smooth scroll) -** https://app.hyfy.io/v/abtqhUOVVTn/
**Navbar**
=> Adjusted the position of navbar links and added smooth scroll feature

css/form.css, index.html
Previously it was not responsive for mobile devices.
=> Responsiveness to contact form added.

css/custom.css, css/imageSlider.css, css/nav_n_btn.css, index.html, js/slider.js
fixes made 
please close issues
=> imageslider / social icons/nav bar done n dusted

css/imageSlider.css, css/nav_n_btn.css, index.html
https://yashsartanpara.github.io/task-master/
=> Landing page as a One Page Template

css/style.css
fixed the footer of login page which was not same as the one in homepage.
=> fixed the footer bug

login.html
there were some js for slider in this page which was throwing error in console.
=> removing unused js from login page

css/signup.css, signup.html
https://souro18.github.io/task-master/signup.html
=> Confirm password button added

css/custom.css, index.html
Please see below page for details
https://creatorisback.github.io/task-master/
=> Footer Issue Fixed

css/custom.css, index.html
Reverts UdacityFrontEndScholarship/task-master#90
=> Revert "Footer Issue Fixed"

css/loader.css, index.html, js/slider.js
Reverts UdacityFrontEndScholarship/task-master#86
=> Revert "fixes"

css/signup.css, signup.html
https://yashsartanpara.github.io/task-master/signup
=> Fix - SignUp page responsiveness and glitch

profile.html
Issue resolved #25 
I have created the basic structure of profile page. Right now buttons are not doing anything for example those icons present are doing nothing. So in future we will make another PR for it to make it working as per our need.
1. Create row with 2 columns as m4 and m8. m4 is responsible for showing each and every task registered by user and m8 is used to show Input, and other cards.
2. For each content I have used card from materialize
3. At top I have created a background which looks similar to Google Forms. For that I created one navigation bar with z-depth-0 and then created another div with absolute position and height of minimum 200px so that it looks like a background image attached with navigation bar
Image:
=> Profile page added

index.html, js/index.js, js/login.js, js/profile.js, js/signup.js, login.html, profile.html, signup.html
=> Made separate js files or each page

css/profile.css, js/profile.js, profile.html
I won't be available for 1 week .so making a PR for my progress with issue #115 because I don't want to slow down progress of the project.
work done:
- separate field for task title and description.
- add task-priority,alarm type
- add task date ,time,task priority,alarm-type in card
- switch button (pending and done) user can mark a task as done
- use less number of colour in page
- edit button on each card clicking on which will open a edit form in modal.
Pending work:
- add scroll feature
- Calendar popup, alarm clock popup(as mentioned in mock up).
Live link: https://souro18.github.io/task-master/profile.html
Mods/co-mods. you can assign the remaining task to someone if they are interested.
=> Adding profile page

css/login.css, css/signup.css, css/style.css, login.html, signup.html
Ref: #117 
Fixed some bugs on the mobile layout of the login/signup page.
**Before:**
*Footer was coming up when keyboard is opened.*
**After:**
Link - http://taskmaster.surge.sh/login.html
**Before:**
*There wasn't any gap between navbar and signup form*
**After:**
Link - http://taskmaster.surge.sh/signup.html
=> Fixed login/signup page mobile layout  bugs

css/form.css, index.html
Fixed the size, color and responsiveness issue of submit button on the homepage under contact section. 
The link for the live page is https://amarjeetsingh1999.github.io/task-master/
=> Resolved Issue #121

css/profile.css, index.html, js/profile.js, profile.html
I have made the 'Deadline date', 'Alarm time' and 'Attachments' icons functional by adding inputs in the 'Add New Task' section of the profile page.
=> Added 'Deadline date', 'Alarm time' and 'Attachments' inputs in 'Add New task' section of Profile page

css/custom.css, index.html
nav-bar links and taskmaster logo hover color change. Here is the live links https://ratnadeepbiswakarma.github.io/task-master/
=> homepage nav-links hover UI

css/custom.css, index.html
Reverts UdacityFrontEndScholarship/task-master#154
=> Revert "homepage nav-links hover UI"

css/custom.css, index.html
Reverts UdacityFrontEndScholarship/task-master#157
=> Revert "Revert "homepage nav-links hover UI""

css/profile.css, profile.html
Task cards with three shades of black(darker black = highest priority, medium black = medium priority, light black = lower priority) this will help the user focus on the most important task and also have added scroll bar
link: https://bhaskarsingh.github.io/task-master/profile
=> Add shades of black according to task priority & scroll bar to task cards

css/fix.css, index.html, js/index.js
Footer n contact section fixes
[live link](https://adi-github.github.io/task-master/)
=> Footer n contact section fixes
